### ISSUE TITLE
[Bug]: Invalid option(s) "queue_name" passed to Messenger transport

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [pimcore/advanced-object-search#239]
### Expected behavior

Alternative messenger transport (redis, amqp, etc.) should be supported.

### Actual behavior

Alternative messengers are not supported as the configuration cannot be correctly changed.

### Steps to reproduce

Switch the default transport (doctrine) to alternative transport

```
framework:
    messenger:
        transports:
            pimcore_index_queues:
                dsn: '%env(AMQP_DSN)%/%2f/pimcore_index_queues'
```

Result: 

`[Symfony\Component\Messenger\Exception\LogicException] Invalid option(s) "queue_name" passed to the AMQP Messenger transport.`

The option `queue_name` is still present in the default config, although it is no longer supported by different transports.

https://github.com/pimcore/advanced-object-search/blob/9a4a7e94a3881ae64cdd120fe7629b49b2755249/src/Resources/config/pimcore/config.yml#L1-L7

Issue widely known in the core and other bundles. We are asking ourself, why it is not fixed here yet?

See:
https://github.com/pimcore/data-importer/issues/226
https://github.com/pimcore/pimcore/issues/11355
https://github.com/pimcore/portal-engine/pull/168
